export enum EcencyWalletCurrency {
  BTC = "btc",
  ETH = "eth",
  APT = "aptos",
  ATOM = "cosmos",
  TON = "ton",
  TRON = "tron",
  SOL = "solana",
  // DOGE = "doge",
  // LTC = "litecoin",
  // ADA = "cardano",
  // STX = "stacks",
  // NEAR = "near",
  // EOS = "eos",
  // SUI = "sui",
}
