name: Publish to npm
on:
  push:
    branches:
      - main
      - app

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - run: cd ./packages/core

      - name: Create .env file
        run: |
          echo "VITE_HELIUS_API_KEY=${{ secrets.VITE_HELIUS_API_KEY }}" >> .env

      - run: cd ../../
      - run: yarn
      - run: yarn build

      - name: Publish @ecency/sdk
        run: |
          cd packages/core
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish @ecency/sdk-wallets
        run: |
          cd packages/wallets
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
